In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("amostra_10pct.csv")

df.columns = ["potencia_ativa", "potencia_reativa", "tensao", "corrente", "sub1", "sub2", "sub3"]
df.head()

   potencia_ativa  potencia_reativa  tensao  corrente  sub1  sub2  sub3
0           1.582             0.198  238.57       6.6   1.0   1.0  19.0
1           2.208             0.062  246.32       8.8   0.0   0.0  19.0
2           0.292             0.082  248.36       1.2   0.0   0.0   0.0
3           0.266             0.082  243.26       1.2   0.0   0.0   0.0
4           1.386             0.000  233.22       5.8   0.0   0.0  17.0

In [3]:
maximo = df["potencia_ativa"].max()
print("Potencia ativa maxima:", maximo)

Potencia ativa maxima: 9.922

In [4]:
limite = maximo * 0.75
print("Limite (75% do maximo):", limite)

acima = df[df["potencia_ativa"] > limite]
acima.head()

Limite (75% do maximo): 7.4415000000000004

      potencia_ativa  potencia_reativa  tensao  corrente  sub1  sub2  sub3
626            7.800             0.686  228.89      34.2  36.0  35.0  16.0
806            7.624             0.130  229.59      33.2  36.0  68.0  16.0
940            8.974             0.576  230.04      39.2  36.0  34.0   0.0
4974           7.856             0.430  232.27      34.0  37.0  27.0  17.0
7184           7.658             0.192  230.92      33.2  36.0  35.0  16.0

In [5]:
quantidade = len(acima)
percentual = quantidade / len(df) * 100
print("Quantidade de registros:", quantidade)
print("Percentual:", round(percentual, 3), "%")

Quantidade de registros: 105
Percentual: 0.051 %

In [6]:
corrente_media = df["corrente"].mean()
print("Corrente media da amostra:", corrente_media)

Corrente media da amostra: 4.629650914793245

In [7]:
acima_dois = df[(df["potencia_ativa"] > limite) & (df["corrente"] > corrente_media)]
print("Quantidade de registros:", len(acima_dois))
acima_dois.head()

Quantidade de registros: 105

      potencia_ativa  potencia_reativa  tensao  corrente  sub1  sub2  sub3
626            7.800             0.686  228.89      34.2  36.0  35.0  16.0
806            7.624             0.130  229.59      33.2  36.0  68.0  16.0
940            8.974             0.576  230.04      39.2  36.0  34.0   0.0
4974           7.856             0.430  232.27      34.0  37.0  27.0  17.0
7184           7.658             0.192  230.92      33.2  36.0  35.0  16.0